import Head from 'next/head';
import Image from 'next/image'
import Link from 'next/link'
// import VideoDubberCard from "./components/VideoDubberCard";
// import { CardsCarousel } from './components/CardsCaraousal';

export default function Home() {
    return (
        <div>
            <Head>
                <title>VideoDubber UI</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className="bg-white shadow-sm">
                <div className="container mx-auto px-4 py-4 flex justify-between items-center">
                    <div className="flex items-center space-x-4">
                        <img src="logo.png" alt="Product Hunt" className="h-8" />
                        <nav className="flex space-x-4">
                            {/* <a href="#" className="text-gray-700 hover:text-gray-900">Launches</a>
                    <a href="#" className="text-gray-700 hover:text-gray-900">Products</a>
                    <a href="#" className="text-gray-700 hover:text-gray-900">News</a>
                    <a href="#" className="text-gray-700 hover:text-gray-900">Community</a>
                    <a href="#" className="text-gray-700 hover:text-gray-900">Advertise</a> */}
                        </nav>
                    </div>
                    <div className="flex items-center space-x-4">
                        <button className="bg-orange-500 text-white px-4 py-2 rounded">Subscribe</button>
                        <button className="bg-gray-300 text-gray-700 px-4 py-2 rounded">Sign in</button>
                    </div>
                </div>
            </header>


            <main className="container w-1/2 mx-auto px-4 py-8">
                <div className="bg-white shadow-sm rounded-lg p-6">
                <img src="product-logo.png" alt="VideoDubber" className=" h-16 " />
                    <div className="flex items-center space-x-4 mb-4">
                        <div>
                            <h1 className="text-2xl font-bold text-gray-900">VideoDubber - Fast Video Translator</h1>
                            <p className= "text-2xl font-light text-gray-600">Translate videos in your own voice, globalize in a click!</p>
                            
                        </div>
                        <div>
                                <button className="bg-orange-500 text-white px-6 py-2 rounded">Visit</button>
                                <button className="ml-1 bg-gray-200 text-gray-700 px-4 py-2 rounded">Upvote 146</button>
                        </div>
                    </div>
                    <div className="flex items-center space-x-4 mb-4">
                        <span className="text-orange-500"><i className="fas fa-clock"></i> 2 months free annually</span>
                        <span className="text-gray-600">Free Options</span>
                    </div>
                    <div className="flex justify-between items-center mb-4">
                        <p className="text-gray-800">Translate video in one click with AI to 150+ languages & accents in original voice. Prime features: 1. 0.1 USD/min for premium video translation with voice cloning 2. Unlimited Editing 3. Exports MP4/SRT/MP3</p>
                    </div>

                </div>

                {/* CAROUSEL CARD HERE */}




                <div id="default-carousel" className="relative w-full" data-carousel="slide">
                    <div className="relative h-56 overflow-hidden rounded-lg md:h-96">
                        <div className="hidden duration-700 ease-in-out" data-carousel-item>
                            <img src="/product-logo.png" className="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="..." />
                        </div>
                        <div className="hidden duration-700 ease-in-out" data-carousel-item>
                            <img src="carousel-1.svg" className="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="..." />
                        </div>
                        <div className="hidden duration-700 ease-in-out" data-carousel-item>
                            <img src="/caraousel.jpg" className="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="..." />
                        </div>
                        <div className="hidden duration-700 ease-in-out" data-carousel-item>
                            <img src="/caraousel.jpg" className="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="..." />
                        </div>
                        <div className="hidden duration-700 ease-in-out" data-carousel-item>
                            <img src="/caraousel.jpg" className="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="..." />
                        </div>
                    </div>
                    <div className="absolute z-30 flex -translate-x-1/2 bottom-5 left-1/2 space-x-3 rtl:space-x-reverse">
                        <button type="button" className="w-3 h-3 rounded-full" aria-current="true" aria-label="Slide 1" data-carousel-slide-to="0"></button>
                        <button type="button" className="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 2" data-carousel-slide-to="1"></button>
                        <button type="button" className="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 3" data-carousel-slide-to="2"></button>
                        <button type="button" className="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 4" data-carousel-slide-to="3"></button>
                        <button type="button" className="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 5" data-carousel-slide-to="4"></button>
                    </div>
                    <button type="button" className="absolute top-0 start-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-prev>
                        <span className="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
                            <svg className="w-4 h-4 text-white dark:text-gray-800 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 1 1 5l4 4" />
                            </svg>
                            <span className="sr-only">Previous</span>
                        </span>
                    </button>
                    <button type="button" className="absolute top-0 end-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-next>
                        <span className="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
                            <svg className="w-4 h-4 text-white dark:text-gray-800 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4" />
                            </svg>
                            <span className="sr-only">Next</span>
                        </span>
                    </button>
                </div>


                <div className="bg-white shadow-sm rounded-lg p-6 mt-6">
                    <h2 className="text-xl font-bold text-gray-900 mb-4">Comments</h2>
                    <div className="space-y-4">

                        <div className="flex space-x-4">
                            <Image width="40" height="40" src="/user-avatar.png" alt="User" className="h-10 w-10 rounded-full" />
                            <div>
                                <h3 className="font-bold text-gray-900">Souvic Chakraborty</h3>
                                <p className="text-gray-700">Hey Product Hunters! We are excited to launch VideoDubber.ai to the Product Hunt community! With VideoDubber.ai, you can translate your videos into 150+ languages & accents using advanced AI-powered voice cloning.</p>
                            </div>
                        </div>

                        <div className="flex space-x-4">
                            <img src="user-avatar.png" alt="User" className="h-10 w-10 rounded-full" />
                            <div>
                                <h3 className="font-bold text-gray-900">Bishakh Ghosh</h3>
                                <p className="text-gray-700">This would definitely save thousands of dollars of dubbing service fees. I think the voice selection is a game changer.</p>
                            </div>
                        </div>

                        <div className="flex space-x-4">
                            <img src="user-avatar.png" alt="User" className="h-10 w-10 rounded-full" />
                            <div>
                                <h3 className="font-bold text-gray-900">Sahil Sagwekar</h3>
                                <p className="text-gray-700">Videodubber is a prime example of AI at its best, enabling content creators to reach billions of viewers while saving valuable time.</p>
                            </div>
                        </div>

                        <div className="flex space-x-4">
                            <img src="user-avatar.png" alt="User" className="h-10 w-10 rounded-full" />
                            <div>
                                <h3 className="font-bold text-gray-900">Olivia Grace</h3>
                                <p className="text-gray-700">No faster tool to translate both audio and subtitles for videos. The review and modify and interface is really helpful.</p>
                            </div>
                        </div>
                    </div>
                </div>

            </main>
        </div>
    );
}
